FROM 084690408984.dkr.ecr.us-east-1.amazonaws.com/oraclejdk-8:v3.0
EXPOSE 8080:8080
COPY target/hello-hotstar-boilerplate-1.0-SNAPSHOT-jar-with-dependencies.jar hello-hotstar-boilerplate.jar
CMD java -jar hello-hotstar-boilerplate.jar